# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20170927_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wall', to='login.User')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='wall',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='login.Wall'),
            preserve_default=False,
        ),
    ]
