# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20170927_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wall',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='wall',
        ),
        migrations.DeleteModel(
            name='Wall',
        ),
    ]
