# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20170927_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='where',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='wall', to='login.User'),
            preserve_default=False,
        ),
    ]
